public DVRecord CreateDVRecord(HSSFSheet sheet){NPOI.HSSF.UserModel.DVConstraint.FormulaPair fp = _constraint.CreateFormulas(sheet);return new DVRecord(_constraint.GetValidationType(),_constraint.Operator,_errorStyle, _emptyCellAllowed, SuppressDropDownArrow,_constraint.GetValidationType() == ValidationType.LIST && _constraint.ExplicitListValues != null,_ShowPromptBox, _prompt_title, _prompt_text,_ShowErrorBox, _error_title, _error_text,fp.Formula1, fp.Formula2,_regions);}
public virtual bool AtMinValue(){return value == minValue;}
public virtual UpdateLifecyclePolicyResponse UpdateLifecyclePolicy(UpdateLifecyclePolicyRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateLifecyclePolicyRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateLifecyclePolicyResponseUnmarshaller.Instance;return Invoke<UpdateLifecyclePolicyResponse>(request, options);}
public JapaneseTokenizerFactory(IDictionary<string, string> args): base(args){Enum.TryParse(Get(args, MODE, JapaneseTokenizer.DEFAULT_MODE.ToString()), true, out mode);userDictionaryPath = Get(args, USER_DICT_PATH);userDictionaryEncoding = Get(args, USER_DICT_ENCODING);discardPunctuation = GetBoolean(args, DISCARD_PUNCTUATION, true);if (args.Count > 0){throw new ArgumentException("Unknown parameters: " + args);}}
public virtual UntagStreamResponse UntagStream(UntagStreamRequest request){var options = new InvokeOptions();options.RequestMarshaller = UntagStreamRequestMarshaller.Instance;options.ResponseUnmarshaller = UntagStreamResponseUnmarshaller.Instance;return Invoke<UntagStreamResponse>(request, options);}
public virtual GetIdentityPoolConfigurationResponse GetIdentityPoolConfiguration(GetIdentityPoolConfigurationRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetIdentityPoolConfigurationRequestMarshaller.Instance;options.ResponseUnmarshaller = GetIdentityPoolConfigurationResponseUnmarshaller.Instance;return Invoke<GetIdentityPoolConfigurationResponse>(request, options);}
public String ResolveNameXText(NameXPtg n){return _iBook.ResolveNameXText(n.SheetRefIndex, n.NameIndex);}
public CreateDBParameterGroupRequest(string dbParameterGroupName, string dbParameterGroupFamily, string description){_dbParameterGroupName = dbParameterGroupName;_dbParameterGroupFamily = dbParameterGroupFamily;_description = description;}
public XPathTokenAnywhereElement(string tokenName, int tokenType): base(tokenName){this.tokenType = tokenType;}
public virtual int lastIndexOf(object @object){object[] snapshot = elements;return lastIndexOf(@object, snapshot, 0, snapshot.Length);}
public virtual UpdateQualificationTypeResponse UpdateQualificationType(UpdateQualificationTypeRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateQualificationTypeRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateQualificationTypeResponseUnmarshaller.Instance;return Invoke<UpdateQualificationTypeResponse>(request, options);}
public virtual UpdateStackResponse UpdateStack(UpdateStackRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateStackRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateStackResponseUnmarshaller.Instance;return Invoke<UpdateStackResponse>(request, options);}
public virtual bool RequiresCommitBody(){return true;}
public virtual DescribeAccountModificationsResponse DescribeAccountModifications(DescribeAccountModificationsRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeAccountModificationsRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeAccountModificationsResponseUnmarshaller.Instance;return Invoke<DescribeAccountModificationsResponse>(request, options);}
public override void write(int oneByte){throw new System.NotImplementedException();}
public virtual DeleteLaunchConfigurationResponse DeleteLaunchConfiguration(DeleteLaunchConfigurationRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteLaunchConfigurationRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteLaunchConfigurationResponseUnmarshaller.Instance;return Invoke<DeleteLaunchConfigurationResponse>(request, options);}
public override string ToString(){return "{" + precedence + ">=prec}?";}
public virtual GetStreamingDistributionResponse GetStreamingDistribution(GetStreamingDistributionRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetStreamingDistributionRequestMarshaller.Instance;options.ResponseUnmarshaller = GetStreamingDistributionResponseUnmarshaller.Instance;return Invoke<GetStreamingDistributionResponse>(request, options);}
public override int DoLogic(){if (name == null || value == null){throw new Exception(GetName() + " - undefined name or value: name=" + name + " value=" + value);}RunData.Config.Set(name, value);return 0;}
public virtual DescribeDomainsResponse DescribeDomains(){return DescribeDomains(new DescribeDomainsRequest());}
public virtual CreateBackupResponse CreateBackup(CreateBackupRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateBackupRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateBackupResponseUnmarshaller.Instance;return Invoke<CreateBackupResponse>(request, options);}
public override String ToString(){StringBuilder buffer = new StringBuilder();buffer.Append(" [FEATURE SMART TAGS]\n");buffer.Append(" [/FEATURE SMART TAGS]\n");return buffer.ToString();}
public RemoveUserFromGroupRequest(string groupName, string userName){_groupName = groupName;_userName = userName;}
public virtual DeleteLexiconResponse DeleteLexicon(DeleteLexiconRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteLexiconRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteLexiconResponseUnmarshaller.Instance;return Invoke<DeleteLexiconResponse>(request, options);}
public UpdateInstanceRequest(): base("Ots", "2016-06-20", "UpdateInstance", "ots", "openAPI"){Method = MethodType.POST;}
public NotImplemented(String functionName){_functionName = functionName;}
public CreateUserInfoRequest(): base("cr", "2016-06-07", "CreateUserInfo", "cr", "openAPI"){UriPattern = "/users";Method = MethodType.PUT;}
public virtual DeleteConfigurationSetEventDestinationResponse DeleteConfigurationSetEventDestination(DeleteConfigurationSetEventDestinationRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteConfigurationSetEventDestinationRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteConfigurationSetEventDestinationResponseUnmarshaller.Instance;return Invoke<DeleteConfigurationSetEventDestinationResponse>(request, options);}
public static BOFRecord CreateSheetBOF(){return new BOFRecord(BOFRecordType.Worksheet);}
public static String Format(String rawSheetName){StringBuilder sb = new StringBuilder(rawSheetName.Length + 2);AppendFormat(sb, rawSheetName);return sb.ToString();}
public virtual UpdateTypedLinkFacetResponse UpdateTypedLinkFacet(UpdateTypedLinkFacetRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateTypedLinkFacetRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateTypedLinkFacetResponseUnmarshaller.Instance;return Invoke<UpdateTypedLinkFacetResponse>(request, options);}
public virtual UpdateMemberResponse UpdateMember(UpdateMemberRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateMemberRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateMemberResponseUnmarshaller.Instance;return Invoke<UpdateMemberResponse>(request, options);}
