public ChartStartBlockRecord(RecordInputStream in1){rt = in1.ReadShort();grbitFrt = in1.ReadShort();iObjectKind = in1.ReadShort();iObjectContext = in1.ReadShort();iObjectInstance1 = in1.ReadShort();iObjectInstance2 = in1.ReadShort();}
public virtual void Fill(int fromIndex, int toIndex, long val){Debug.Assert(val <= MaxValue(BitsPerValue));Debug.Assert(fromIndex <= toIndex);for (int i = fromIndex; i < toIndex; ++i){Set(i, val);}}
public virtual void SetStreamFileThreshold(int newLimit){streamFileThreshold = newLimit;}
public virtual DescribeStackDriftDetectionStatusResponse DescribeStackDriftDetectionStatus(DescribeStackDriftDetectionStatusRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeStackDriftDetectionStatusRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeStackDriftDetectionStatusResponseUnmarshaller.Instance;return Invoke<DescribeStackDriftDetectionStatusResponse>(request, options);}
public override void Serialize(ILittleEndianOutput out1){futureHeader.Serialize(out1);out1.WriteShort(isf_sharedFeatureType);out1.WriteByte(reserved);out1.WriteInt((int)cbHdrData);out1.Write(rgbHdrData);}
public virtual StopContactResponse StopContact(StopContactRequest request){var options = new InvokeOptions();options.RequestMarshaller = StopContactRequestMarshaller.Instance;options.ResponseUnmarshaller = StopContactResponseUnmarshaller.Instance;return Invoke<StopContactResponse>(request, options);}
public virtual int ByteAt(int idx){return bytes[idx].Value;}
public override Explanation Explain(int doc, Explanation freq){Explanation expl = new Explanation(Score(doc, freq.Value), "sum of:");foreach (SimScorer subScorer in subScorers){expl.AddDetail(subScorer.Explain(doc, freq));}return expl;}
public virtual CreateSmsTemplateResponse CreateSmsTemplate(CreateSmsTemplateRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateSmsTemplateRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateSmsTemplateResponseUnmarshaller.Instance;return Invoke<CreateSmsTemplateResponse>(request, options);}
public virtual DisassociatePhoneNumberFromUserResponse DisassociatePhoneNumberFromUser(DisassociatePhoneNumberFromUserRequest request){var options = new InvokeOptions();options.RequestMarshaller = DisassociatePhoneNumberFromUserRequestMarshaller.Instance;options.ResponseUnmarshaller = DisassociatePhoneNumberFromUserResponseUnmarshaller.Instance;return Invoke<DisassociatePhoneNumberFromUserResponse>(request, options);}
public override String ToString(){StringBuilder buffer = new StringBuilder();buffer.Append("[EXTSST]\n");buffer.Append("    .streampos      = ").Append(StringUtil.ToHexString(StreamPos)).Append("\n");buffer.Append("    .bucketsstoffset= ").Append(StringUtil.ToHexString(BucketSSTOffset)).Append("\n");buffer.Append("    .zero           = ").Append(StringUtil.ToHexString(field_3_zero)).Append("\n");buffer.Append("[/EXTSST]\n");return buffer.ToString();}
public virtual CleanCommand Clean(){return new CleanCommand(repo);}
public CellRangeAddress GetCellRangeAddress(int index){return (CellRangeAddress)_list[index];}
public ApostropheFilterFactory(IDictionary<string, string> args): base(args){if (args.Count > 0){throw new System.ArgumentException("Unknown parameter(s): " + args);}}
public static int CommitMessage(byte[] b, int ptr){int sz = b.Length;if (ptr == 0){ptr += 46;}while (ptr < sz && b[ptr] == 'p'){ptr += 48;}return TagMessage(b, ptr);}
public CustomViewSettingsRecordAggregate(RecordStream rs){_begin = rs.GetNext();if (_begin.Sid != UserSViewBegin.sid){throw new InvalidOperationException("Bad begin record");}List<RecordBase> temp = new List<RecordBase>();while (rs.PeekNextSid() != UserSViewEnd.sid){if (PageSettingsBlock.IsComponentRecord(rs.PeekNextSid())){if (_psBlock != null){throw new InvalidOperationException("Found more than one PageSettingsBlock in custom view Settings sub-stream");}_psBlock = new PageSettingsBlock(rs);temp.Add(_psBlock);continue;}temp.Add(rs.GetNext());}_recs = temp;_end = rs.GetNext(); if (_end.Sid != UserSViewEnd.sid){throw new InvalidOperationException("Bad custom view Settings end record");}}
public virtual ICollection<PackFile> GetPacks(){ObjectDirectory.PackList list = packList.Get();if (list == NO_PACKS){list = ScanPacks(list);}PackFile[] packs = list.packs;return Sharpen.Collections.UnmodifiableCollection(Arrays.AsList(packs));}
public SQLException(string error) : base(error){throw new System.NotImplementedException();}
public virtual string ToExternalString(){StringBuilder r = new StringBuilder();r.Append(GetName());r.Append(" <");r.Append(GetEmailAddress());r.Append("> ");r.Append(when / 1000);r.Append(' ');AppendTimezone(r);return r.ToString();}
public IntMapper(int InitialCapacity){elements = new List<T>(InitialCapacity);valueKeyMap = new Dictionary<T, int>(InitialCapacity);}
public virtual PersonIdent GetSourceCommitter(){RevCommit c = GetSourceCommit();return c != null ? c.GetCommitterIdent() : null;}
public CharVector(int capacity){if (capacity > 0){blockSize = capacity;}else{blockSize = DEFAULT_BLOCK_SIZE;}array = new char[blockSize];n = 0;}
public virtual int size(){lock (mutex){return c.size();}}
public Int64sRef Next(int count){Debug.Assert(count > 0);if (ord == valueCount){throw new System.IO.EndOfStreamException();}if (off == blockSize){Refill();}count = Math.Min(count, blockSize - off);count = (int)Math.Min(count, valueCount - ord);valuesRef.Offset = off;valuesRef.Length = count;off += count;ord += count;return valuesRef;}
public virtual GetHealthCheckCountResponse GetHealthCheckCount(GetHealthCheckCountRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetHealthCheckCountRequestMarshaller.Instance;options.ResponseUnmarshaller = GetHealthCheckCountResponseUnmarshaller.Instance;return Invoke<GetHealthCheckCountResponse>(request, options);}
public override java.nio.LongBuffer compact(){System.Array.Copy(backingArray, _position + offset, backingArray, offset, remaining());_position = _limit - _position;_limit = _capacity;_mark = UNSET_MARK;return this;}
public virtual string GetTextAsString(){if (this.m_text == null)return null;else return this.m_text.ToString();}
public virtual UpdateCustomVerificationEmailTemplateResponse UpdateCustomVerificationEmailTemplate(UpdateCustomVerificationEmailTemplateRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateCustomVerificationEmailTemplateRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateCustomVerificationEmailTemplateResponseUnmarshaller.Instance;return Invoke<UpdateCustomVerificationEmailTemplateResponse>(request, options);}
public int GetExternalSheetIndex(String workbookName, String sheetName){return OrCreateLinkTable.GetExternalSheetIndex(workbookName, sheetName, sheetName);}
public override String ToString(){StringBuilder sb = new StringBuilder();String recordName = this.RecordName;sb.Append("[").Append(recordName).Append("]\n");sb.Append("    .row    = ").Append(HexDump.ShortToHex(Row)).Append("\n");sb.Append("    .col    = ").Append(HexDump.ShortToHex(Column)).Append("\n");if (IsBiff2){sb.Append("    .cellattrs = ").Append(HexDump.ShortToHex(CellAttrs)).Append("\n");}else{sb.Append("    .xFindex   = ").Append(HexDump.ShortToHex(XFIndex)).Append("\n");}AppendValueText(sb);sb.Append("\n");sb.Append("[/").Append(recordName).Append("]\n");return sb.ToString();}
public virtual DescribeTypeRegistrationResponse DescribeTypeRegistration(DescribeTypeRegistrationRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeTypeRegistrationRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeTypeRegistrationResponseUnmarshaller.Instance;return Invoke<DescribeTypeRegistrationResponse>(request, options);}
public FeatHdrRecord(){futureHeader = new FtrHeader();futureHeader.RecordType = (sid);}
