public POIFSDocumentPath(){this.components = new string[0];}
public virtual UpdateLinkAttributesResponse UpdateLinkAttributes(UpdateLinkAttributesRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateLinkAttributesRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateLinkAttributesResponseUnmarshaller.Instance;return Invoke<UpdateLinkAttributesResponse>(request, options);}
public void Write(OpenStringBuilder arr){Write(arr.m_buf, 0, arr.Length); }
public virtual DeleteVpnConnectionRouteResponse DeleteVpnConnectionRoute(DeleteVpnConnectionRouteRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteVpnConnectionRouteRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteVpnConnectionRouteResponseUnmarshaller.Instance;return Invoke<DeleteVpnConnectionRouteResponse>(request, options);}
public virtual DeleteSignalingChannelResponse DeleteSignalingChannel(DeleteSignalingChannelRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteSignalingChannelRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteSignalingChannelResponseUnmarshaller.Instance;return Invoke<DeleteSignalingChannelResponse>(request, options);}
public virtual UpdateDetectorVersionMetadataResponse UpdateDetectorVersionMetadata(UpdateDetectorVersionMetadataRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateDetectorVersionMetadataRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateDetectorVersionMetadataResponseUnmarshaller.Instance;return Invoke<UpdateDetectorVersionMetadataResponse>(request, options);}
public override Explanation Explain(int doc, Explanation freq){Explanation expl = new Explanation(Score(doc, freq.Value), "sum of:");foreach (SimScorer subScorer in subScorers){expl.AddDetail(subScorer.Explain(doc, freq));}return expl;}
public override ValueEval Evaluate(int srcRowIndex, int srcColumnIndex, ValueEval arg0,ValueEval arg1){String arg;int index;try{arg = TextFunction.EvaluateStringArg(arg0, srcRowIndex, srcColumnIndex);index = TextFunction.EvaluateIntArg(arg1, srcRowIndex, srcColumnIndex);}catch (EvaluationException e){return e.GetErrorEval();}if (index < 0){return ErrorEval.VALUE_INVALID;}String result;if (_isLeft){result = arg.Substring(0, Math.Min(arg.Length, index));}else{result = arg.Substring(Math.Max(0, arg.Length - index));}return new StringEval(result);}
public override void Decode(byte[] blocks, int blocksOffset, int[] values, int valuesOffset, int iterations){for (int i = 0; i < iterations; ++i){int byte0 = blocks[blocksOffset++] & 0xFF;values[valuesOffset++] = (int)((uint)byte0 >> 5);values[valuesOffset++] = ((int)((uint)byte0 >> 2)) & 7;int byte1 = blocks[blocksOffset++] & 0xFF;values[valuesOffset++] = ((byte0 & 3) << 1) | ((int)((uint)byte1 >> 7));values[valuesOffset++] = ((int)((uint)byte1 >> 4)) & 7;values[valuesOffset++] = ((int)((uint)byte1 >> 1)) & 7;int byte2 = blocks[blocksOffset++] & 0xFF;values[valuesOffset++] = ((byte1 & 1) << 2) | ((int)((uint)byte2 >> 6));values[valuesOffset++] = ((int)((uint)byte2 >> 3)) & 7;values[valuesOffset++] = byte2 & 7;}}
public virtual void throwException(){switch (this.type){case TYPE_UNDERFLOW:{throw new java.nio.BufferUnderflowException();}case TYPE_OVERFLOW:{throw new java.nio.BufferOverflowException();}case TYPE_UNMAPPABLE_CHAR:{throw new java.nio.charset.UnmappableCharacterException(this._length);}case TYPE_MALFORMED_INPUT:{throw new java.nio.charset.MalformedInputException(this._length);}default:{throw new java.nio.charset.CharacterCodingException();}}}
public override void jumpDrawablesToCurrentState(){base.jumpDrawablesToCurrentState();if (mThumb != null){mThumb.jumpToCurrentState();}}
public void RemoveCell(CellValueRecordInterface cell){if (cell == null){throw new ArgumentException("cell must not be null");}int row = cell.Row;if (row >= records.Length){throw new Exception("cell row is out of range");}CellValueRecordInterface[] rowCells = records[row];if (rowCells == null){throw new Exception("cell row is already empty");}int column = cell.Column;if (column >= rowCells.Length){throw new Exception("cell column is out of range");}rowCells[column] = null;}
public virtual DescribeDBClustersResponse DescribeDBClusters(DescribeDBClustersRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeDBClustersRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeDBClustersResponseUnmarshaller.Instance;return Invoke<DescribeDBClustersResponse>(request, options);}
public java.lang.StringBuffer append(bool b){return append(b ? "true" : "false");}
public override int Preceding(int pos){if (pos < start || pos > end){throw new ArgumentException("offset out of bounds");}else if (pos == start){current = start;return Done;}else{return First();}}
public static Type LookupClass(string name){return loader.LookupClass(name);}
public virtual GetDocumentVersionResponse GetDocumentVersion(GetDocumentVersionRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetDocumentVersionRequestMarshaller.Instance;options.ResponseUnmarshaller = GetDocumentVersionResponseUnmarshaller.Instance;return Invoke<GetDocumentVersionResponse>(request, options);}
public static void fill(char[] array, char value){{for (int i = 0; i < array.Length; i++){array[i] = value;}}}
public AxisRecord(RecordInputStream in1){field_1_axisType = in1.ReadShort();field_2_reserved1 = in1.ReadInt();field_3_reserved2 = in1.ReadInt();field_4_reserved3 = in1.ReadInt();field_5_reserved4 = in1.ReadInt();}
public virtual DescribeClusterSecurityGroupsResponse DescribeClusterSecurityGroups(){return DescribeClusterSecurityGroups(new DescribeClusterSecurityGroupsRequest());}
public override object[] toArray(){int index = 0;object[] contents = new object[_size];java.util.LinkedList.Link<E> link = voidLink.next;while (link != voidLink){contents[index++] = link.data;link = link.next;}return contents;}
public virtual DescribeOptionGroupsResponse DescribeOptionGroups(){return DescribeOptionGroups(new DescribeOptionGroupsRequest());}
public virtual GetCelebrityInfoResponse GetCelebrityInfo(GetCelebrityInfoRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetCelebrityInfoRequestMarshaller.Instance;options.ResponseUnmarshaller = GetCelebrityInfoResponseUnmarshaller.Instance;return Invoke<GetCelebrityInfoResponse>(request, options);}
public override String ToString(){StringBuilder sb = new StringBuilder();sb.Append("[").Append("USERSVIEWEND").Append("] (0x");sb.Append(StringUtil.ToHexString(sid).ToUpper() + ")\n");sb.Append("  rawData=").Append(HexDump.ToHex(_rawData)).Append("\n");sb.Append("[/").Append("USERSVIEWEND").Append("]\n");return sb.ToString();}
public virtual ParseTreeMatch Match(IParseTree tree){return matcher.Match(tree, this);}
public virtual ResetNetworkInterfaceAttributeResponse ResetNetworkInterfaceAttribute(ResetNetworkInterfaceAttributeRequest request){var options = new InvokeOptions();options.RequestMarshaller = ResetNetworkInterfaceAttributeRequestMarshaller.Instance;options.ResponseUnmarshaller = ResetNetworkInterfaceAttributeResponseUnmarshaller.Instance;return Invoke<ResetNetworkInterfaceAttributeResponse>(request, options);}
public override String ToFormulaString(){throw Invalid();}
public virtual DescribeRepositoryAssociationResponse DescribeRepositoryAssociation(DescribeRepositoryAssociationRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeRepositoryAssociationRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeRepositoryAssociationResponseUnmarshaller.Instance;return Invoke<DescribeRepositoryAssociationResponse>(request, options);}
public virtual ListDeploymentConfigsResponse ListDeploymentConfigs(){return ListDeploymentConfigs(new ListDeploymentConfigsRequest());}
public virtual DisassociateRouteTableResponse DisassociateRouteTable(DisassociateRouteTableRequest request){var options = new InvokeOptions();options.RequestMarshaller = DisassociateRouteTableRequestMarshaller.Instance;options.ResponseUnmarshaller = DisassociateRouteTableResponseUnmarshaller.Instance;return Invoke<DisassociateRouteTableResponse>(request, options);}
public override void Serialize(ILittleEndianOutput out1){out1.WriteShort(m_formats.Count);for (int i = 0; i < m_formats.Count; i++){((CTFormat)m_formats[i]).Serialize(out1);}}
public ValueEval Evaluate(ValueEval[] args, OperationEvaluationContext ec){double result;if (args.Length != 2){return ErrorEval.VALUE_INVALID;}try{double startDateAsNumber = GetValue(args[0]);int offsetInMonthAsNumber = (int)GetValue(args[1]);DateTime startDate = DateUtil.GetJavaDate(startDateAsNumber);DateTime resultDate = startDate.AddMonths(offsetInMonthAsNumber);result = DateUtil.GetExcelDate(resultDate);NumericFunction.CheckValue(result);return new NumberEval(result);}catch (EvaluationException e){return e.GetErrorEval();}}
public virtual GetBlockResponse GetBlock(GetBlockRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetBlockRequestMarshaller.Instance;options.ResponseUnmarshaller = GetBlockResponseUnmarshaller.Instance;return Invoke<GetBlockResponse>(request, options);}
public virtual DisassociateResolverEndpointIpAddressResponse DisassociateResolverEndpointIpAddress(DisassociateResolverEndpointIpAddressRequest request){var options = new InvokeOptions();options.RequestMarshaller = DisassociateResolverEndpointIpAddressRequestMarshaller.Instance;options.ResponseUnmarshaller = DisassociateResolverEndpointIpAddressResponseUnmarshaller.Instance;return Invoke<DisassociateResolverEndpointIpAddressResponse>(request, options);}
public override bool Equals(object obj){if (this == obj)return true;if (obj == null)return false;if (GetType() != obj.GetType())return false;SegToken other = (SegToken)obj;if (!Arrays.Equals(CharArray, other.CharArray))return false;if (EndOffset != other.EndOffset)return false;if (Index != other.Index)return false;if (StartOffset != other.StartOffset)return false;if (Weight != other.Weight)return false;if (WordType != other.WordType)return false;return true;}
public virtual CleanCommand Clean(){return new CleanCommand(repo);}
public virtual ListStackInstancesResponse ListStackInstances(ListStackInstancesRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListStackInstancesRequestMarshaller.Instance;options.ResponseUnmarshaller = ListStackInstancesResponseUnmarshaller.Instance;return Invoke<ListStackInstancesResponse>(request, options);}
public ValueEval Evaluate(ValueEval[] args, int srcCellRow, int srcCellCol){double result;try{IList temp = new ArrayList();for (int i = 0; i < args.Length; i++){CollectValues(args[i], temp);}double[] values = new double[temp.Count];for (int i = 0; i < values.Length; i++){values[i] = (Double)temp[i];}result = Evaluate(values);}catch (EvaluationException e){return e.GetErrorEval();}return new NumberEval(result);}
public virtual CreateAssessmentTemplateResponse CreateAssessmentTemplate(CreateAssessmentTemplateRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateAssessmentTemplateRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateAssessmentTemplateResponseUnmarshaller.Instance;return Invoke<CreateAssessmentTemplateResponse>(request, options);}
public override string ToString(){StringBuilder r = new StringBuilder();r.Append("(");for (int i = 0; i < subfilters.Length; i++){if (i > 0){r.Append(" OR ");}r.Append(subfilters[i].ToString());}r.Append(")");return r.ToString();}
public TreeSet(){backingMap = new java.util.TreeMap<E, object>();}
public virtual void Fill(int fromIndex, int toIndex, long val){Debug.Assert(val <= MaxValue(BitsPerValue));Debug.Assert(fromIndex <= toIndex);for (int i = fromIndex; i < toIndex; ++i){Set(i, val);}}
public override object[] toArray(){lock (this._enclosing){return base.toArray();}}
public virtual DescribeFlowLogsResponse DescribeFlowLogs(DescribeFlowLogsRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeFlowLogsRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeFlowLogsResponseUnmarshaller.Instance;return Invoke<DescribeFlowLogsResponse>(request, options);}
public ValueEval GetRef3DEval(Ref3DPxg rptg){SheetRangeEvaluator sre = CreateExternSheetRefEvaluator(rptg.SheetName, rptg.LastSheetName, rptg.ExternalWorkbookNumber);return new LazyRefEval(rptg.Row, rptg.Column, sre);}
public virtual ListMetricsResponse ListMetrics(){return ListMetrics(new ListMetricsRequest());}
public override String ToString(){StringBuilder buffer = new StringBuilder();buffer.Append("[REFRESHALL]\n");buffer.Append("    .refreshall      = ").Append(RefreshAll).Append("\n");buffer.Append("[/REFRESHALL]\n");return buffer.ToString();}
public virtual org.xmlpull.v1.XmlPullParser newPullParser(){if (parserClasses == null){throw new org.xmlpull.v1.XmlPullParserException("Factory initialization was incomplete - has not tried "+ classNamesLocation);}if (parserClasses.size() == 0){throw new org.xmlpull.v1.XmlPullParserException("No valid parser classes found in "+ classNamesLocation);}java.lang.StringBuilder issues = new java.lang.StringBuilder();{for (int i = 0; i < parserClasses.size(); i++){System.Type ppClass = (System.Type)parserClasses.get(i);try{org.xmlpull.v1.XmlPullParser pp = (org.xmlpull.v1.XmlPullParser)System.Activator.CreateInstance(ppClass);{for (java.util.Iterator<object> iter = features.keySet().iterator(); iter.hasNext(); ){string key = (string)iter.next();bool value = (bool)features.get(key);if (value != null && value){pp.setFeature(key, true);}}}return pp;}catch (System.Exception ex){issues.append(ppClass.FullName + ": " + ex.ToString() + "; ");}}}throw new org.xmlpull.v1.XmlPullParserException("could not create parser: " + issues);}
public override java.nio.DoubleBuffer duplicate(){java.nio.ByteBuffer bb = byteBuffer.duplicate().order(byteBuffer.order());java.nio.DoubleToByteBufferAdapter buf = new java.nio.DoubleToByteBufferAdapter(bb);buf._limit = _limit;buf._position = _position;buf._mark = _mark;return buf;}
public override java.nio.ByteBuffer put(byte b){throw new java.nio.ReadOnlyBufferException();}
public override void Validate(){base.Validate();}
public virtual DecreaseReplicationFactorResponse DecreaseReplicationFactor(DecreaseReplicationFactorRequest request){var options = new InvokeOptions();options.RequestMarshaller = DecreaseReplicationFactorRequestMarshaller.Instance;options.ResponseUnmarshaller = DecreaseReplicationFactorResponseUnmarshaller.Instance;return Invoke<DecreaseReplicationFactorResponse>(request, options);}
public virtual StopContactResponse StopContact(StopContactRequest request){var options = new InvokeOptions();options.RequestMarshaller = StopContactRequestMarshaller.Instance;options.ResponseUnmarshaller = StopContactResponseUnmarshaller.Instance;return Invoke<StopContactResponse>(request, options);}
public virtual DescribeVolumeStatusResponse DescribeVolumeStatus(DescribeVolumeStatusRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeVolumeStatusRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeVolumeStatusResponseUnmarshaller.Instance;return Invoke<DescribeVolumeStatusResponse>(request, options);}
public virtual ICollection<string> GetNames(string section){return GetNames(section, null);}
public java.lang.StringBuffer insert(int index, float f){return insert(index, System.Convert.ToString(f));}
public override int Advance(int target){upto++;if (upto == docIDs.Length){return docID_Renamed = NO_MORE_DOCS;}int inc = 10;int nextUpto = upto + 10;int low;int high;while (true){if (nextUpto >= docIDs.Length){low = nextUpto - inc;high = docIDs.Length - 1;break;}if (target <= docIDs[nextUpto]){low = nextUpto - inc;high = nextUpto;break;}inc *= 2;nextUpto += inc;}while (true){if (low > high){upto = low;break;}int mid = (int) ((uint) (low + high) >> 1);int cmp = docIDs[mid] - target;if (cmp < 0){low = mid + 1;}else if (cmp > 0){high = mid - 1;}else{upto = mid;break;}}if (liveDocs != null){while (upto < docIDs.Length){if (liveDocs.Get(docIDs[upto])){break;}upto++;}}if (upto == docIDs.Length){return docID_Renamed = NO_MORE_DOCS;}else{return docID_Renamed = docIDs[upto];}}
public override void SetParams(string @params){base.SetParams(@params);int k = @params.IndexOf(',');name = @params.Substring(0, k - 0).Trim();value = @params.Substring(k + 1).Trim();}
public IgnoreNode(IList<IgnoreRule> rules){this.rules = rules;}
public E next(){if (iterator.nextIndex() < end){return iterator.next();}throw new java.util.NoSuchElementException();}
public override String ToString(){StringBuilder sb = new StringBuilder();String recordName = this.RecordName;sb.Append("[").Append(recordName).Append("]\n");sb.Append("    .row    = ").Append(HexDump.ShortToHex(Row)).Append("\n");sb.Append("    .col    = ").Append(HexDump.ShortToHex(Column)).Append("\n");if (IsBiff2){sb.Append("    .cellattrs = ").Append(HexDump.ShortToHex(CellAttrs)).Append("\n");}else{sb.Append("    .xFindex   = ").Append(HexDump.ShortToHex(XFIndex)).Append("\n");}AppendValueText(sb);sb.Append("\n");sb.Append("[/").Append(recordName).Append("]\n");return sb.ToString();}
public virtual GetApplicationResponse GetApplication(GetApplicationRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetApplicationRequestMarshaller.Instance;options.ResponseUnmarshaller = GetApplicationResponseUnmarshaller.Instance;return Invoke<GetApplicationResponse>(request, options);}
public long RamBytesUsed(){long sizeInBytes = 0;sizeInBytes += RamUsageEstimator.SizeOf(minValues);sizeInBytes += RamUsageEstimator.SizeOf(averages);foreach (PackedInt32s.Reader reader in subReaders){sizeInBytes += reader.RamBytesUsed();}return sizeInBytes;}
public virtual DescribeRouteTablesResponse DescribeRouteTables(){return DescribeRouteTables(new DescribeRouteTablesRequest());}
public DescribeTagsRequest(List<Filter> filters){_filters = filters;}
public override string ToString(){return "(" + a.ToString() + " OR " + b.ToString() + ")";}
public virtual DescribeCompanyNetworkConfigurationResponse DescribeCompanyNetworkConfiguration(DescribeCompanyNetworkConfigurationRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeCompanyNetworkConfigurationRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeCompanyNetworkConfigurationResponseUnmarshaller.Instance;return Invoke<DescribeCompanyNetworkConfigurationResponse>(request, options);}
public virtual int ByteAt(int idx){return bytes[idx].Value;}
public override int get(int index){checkIndex(index);return byteBuffer.getInt(index * libcore.io.SizeOf.INT);}
public static double var(double[] v){double r = Double.NaN;if (v != null && v.Length > 1){r = devsq(v) / (v.Length - 1);}return r;}
public override WAH8DocIdSet Build(){if (this.wordNum != -1){AddWord(wordNum, (byte)word);}return base.Build();}
public virtual int GetWeight(){return WEIGHT_UNKNOWN;}
public void IncRef(){EnsureOpen();refCount.IncrementAndGet();}
public virtual ListFragmentsResponse ListFragments(ListFragmentsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListFragmentsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListFragmentsResponseUnmarshaller.Instance;return Invoke<ListFragmentsResponse>(request, options);}
public override int FillFields(byte[] data, int offset, IEscherRecordFactory recordFactory){int bytesAfterHeader = ReadHeader(data, offset);int pos = offset + HEADER_SIZE;field_1_UID = new byte[16];Array.Copy(data, pos, field_1_UID, 0, 16); pos += 16;field_2_marker = data[pos]; pos++;field_pictureData = new byte[bytesAfterHeader - 17];Array.Copy(data, pos, field_pictureData, 0, field_pictureData.Length);return bytesAfterHeader + HEADER_SIZE;}
public virtual ICollection<string> GetNames(string section, string subsection){return GetState().GetNames(section, subsection);}
public override bool Equals(object o){if (!(o is DisjunctionMaxQuery)){return false;}DisjunctionMaxQuery other = (DisjunctionMaxQuery)o;return this.Boost == other.Boost&& this.tieBreakerMultiplier == other.tieBreakerMultiplier&& this.disjuncts.Equals(other.disjuncts);}
public static FormulaError ForInt(int type){if (imap.ContainsKey(type))return imap[type];if (bmap.ContainsKey((byte)type))return bmap[(byte)type];throw new ArgumentException("Unknown error type: " + type);}
public override bool Equals(object obj){if (this == obj){return true;}if (obj == null){return false;}if (GetType() != obj.GetType()){return false;}WeightedPhraseInfo other = (WeightedPhraseInfo)obj;if (StartOffset != other.StartOffset){return false;}if (EndOffset != other.EndOffset){return false;}if (Boost != other.Boost){return false;}return true;}
public virtual bool remove(object o){lock (this){int index = indexOf(o);if (index == -1){return false;}remove(index);return true;}}
public string[] GetValues(string name){var result = new List<string>();foreach (IIndexableField field in fields){if (field.Name.Equals(name, StringComparison.Ordinal) && field.GetStringValue() != null){result.Add(field.GetStringValue());}}if (result.Count == 0){return NO_STRINGS;}return result.ToArray();}
public virtual DeleteApplicationSnapshotResponse DeleteApplicationSnapshot(DeleteApplicationSnapshotRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteApplicationSnapshotRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteApplicationSnapshotResponseUnmarshaller.Instance;return Invoke<DeleteApplicationSnapshotResponse>(request, options);}
public bool hasTransparentBounds(){return transparentBounds;}
public virtual int size(){lock (mutex){return c.size();}}
public override java.nio.ShortBuffer put(short[] src, int srcOffset, int shortCount){if (shortCount > remaining()){throw new java.nio.BufferOverflowException();}System.Array.Copy(src, srcOffset, backingArray, offset + _position, shortCount);_position += shortCount;return this;}
public override void Close(){if (sock != null){try{sch.ReleaseSession(sock);}finally{sock = null;}}}
public virtual void SetDetachingSymbolicRef(){detachingSymbolicRef = true;}
public override TokenStream Create(TokenStream input){return new SoraniStemFilter(input);}
public virtual GetTranscriptResponse GetTranscript(GetTranscriptRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetTranscriptRequestMarshaller.Instance;options.ResponseUnmarshaller = GetTranscriptResponseUnmarshaller.Instance;return Invoke<GetTranscriptResponse>(request, options);}
public virtual DescribeProblemObservationsResponse DescribeProblemObservations(DescribeProblemObservationsRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeProblemObservationsRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeProblemObservationsResponseUnmarshaller.Instance;return Invoke<DescribeProblemObservationsResponse>(request, options);}
public virtual RegisterTypeResponse RegisterType(RegisterTypeRequest request){var options = new InvokeOptions();options.RequestMarshaller = RegisterTypeRequestMarshaller.Instance;options.ResponseUnmarshaller = RegisterTypeResponseUnmarshaller.Instance;return Invoke<RegisterTypeResponse>(request, options);}
public override object ToObject(){return Exists ? (object)Value : null;}
public virtual CreatePipelineResponse CreatePipeline(CreatePipelineRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreatePipelineRequestMarshaller.Instance;options.ResponseUnmarshaller = CreatePipelineResponseUnmarshaller.Instance;return Invoke<CreatePipelineResponse>(request, options);}
public virtual void write(byte[] buffer, int byteOffset, int byteCount){throw new System.NotImplementedException();}
public virtual PutBlockPublicAccessConfigurationResponse PutBlockPublicAccessConfiguration(PutBlockPublicAccessConfigurationRequest request){var options = new InvokeOptions();options.RequestMarshaller = PutBlockPublicAccessConfigurationRequestMarshaller.Instance;options.ResponseUnmarshaller = PutBlockPublicAccessConfigurationResponseUnmarshaller.Instance;return Invoke<PutBlockPublicAccessConfigurationResponse>(request, options);}
public virtual void EndWorker(){if (workers.DecrementAndGet() == 0){process.Release();}}
public HSSFShapeGroup CreateGroup(HSSFChildAnchor anchor){HSSFShapeGroup group = new HSSFShapeGroup(this, anchor);group.Parent = this;group.Anchor = anchor;shapes.Add(group);OnCreate(group);return group;}
public virtual CreateSecurityGroupResponse CreateSecurityGroup(CreateSecurityGroupRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateSecurityGroupRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateSecurityGroupResponseUnmarshaller.Instance;return Invoke<CreateSecurityGroupResponse>(request, options);}
public override ObjectId GetResultTreeId(){return (resultTree == null) ? null : resultTree.ToObjectId();}
public virtual DeleteEnvironmentResponse DeleteEnvironment(DeleteEnvironmentRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteEnvironmentRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteEnvironmentResponseUnmarshaller.Instance;return Invoke<DeleteEnvironmentResponse>(request, options);}
