public virtual CopyWorkspaceImageResponse CopyWorkspaceImage(CopyWorkspaceImageRequest request){var options = new InvokeOptions();options.RequestMarshaller = CopyWorkspaceImageRequestMarshaller.Instance;options.ResponseUnmarshaller = CopyWorkspaceImageResponseUnmarshaller.Instance;return Invoke<CopyWorkspaceImageResponse>(request, options);}
public override java.nio.CharBuffer slice(){byteBuffer.limit(_limit * libcore.io.SizeOf.CHAR);byteBuffer.position(_position * libcore.io.SizeOf.CHAR);java.nio.ByteBuffer bb = byteBuffer.slice().order(byteBuffer.order());java.nio.CharBuffer result = new java.nio.CharToByteBufferAdapter(bb);byteBuffer.clear();return result;}
public override ValueEval Evaluate(int srcRowIndex, int srcColumnIndex, ValueEval textArg){ValueEval veText1;try{veText1 = OperandResolver.GetSingleValue(textArg, srcRowIndex, srcColumnIndex);}catch (EvaluationException e){return e.GetErrorEval();}String text = OperandResolver.CoerceValueToString(veText1);if (text.Length == 0){return ErrorEval.VALUE_INVALID;}int code = (int)text[0];return new StringEval(code.ToString());}
public void SwitchTo(int lexState){if (lexState >= 2 || lexState < 0)throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);elsecurLexState = lexState;}
public override java.nio.ShortBuffer slice(){return new java.nio.ReadOnlyShortArrayBuffer(remaining(), backingArray, offset +_position);}
public NameCommentRecord(RecordInputStream ris){ILittleEndianInput in1 = ris;field_1_record_type = in1.ReadShort();field_2_frt_cell_ref_flag = in1.ReadShort();field_3_reserved = in1.ReadLong();int field_4_name_length = in1.ReadShort();int field_5_comment_length = in1.ReadShort();in1.ReadByte(); field_6_name_text = StringUtil.ReadCompressedUnicode(in1, field_4_name_length);in1.ReadByte(); field_7_comment_text = StringUtil.ReadCompressedUnicode(in1, field_5_comment_length);}
public override ValueEval Evaluate(int srcRowIndex, int srcColumnIndex, ValueEval arg0){ValueEval ve;try{ve = OperandResolver.GetSingleValue(arg0, srcRowIndex, srcColumnIndex);}catch (EvaluationException e){ve = e.GetErrorEval();}return BoolEval.ValueOf(Evaluate(ve));}
public virtual int OrdVal(int doc){throw new System.NotSupportedException();}
public virtual GetStatusResponse GetStatus(GetStatusRequest request){var options = new InvokeOptions();options.RequestMarshaller = GetStatusRequestMarshaller.Instance;options.ResponseUnmarshaller = GetStatusResponseUnmarshaller.Instance;return Invoke<GetStatusResponse>(request, options);}
public static void ByteArray(StringBuilder buffer, byte[] bytes){for (int i = 0; i < bytes.Length; i++){buffer.Append("b[").Append(i).Append("]=").Append(bytes[i]);if (i < bytes.Length - 1){buffer.Append(',');}}}
public sealed override byte get(){if (_position == _limit){throw new java.nio.BufferUnderflowException();}return backingArray[offset + _position++];}
public virtual DescribeTrafficMirrorTargetsResponse DescribeTrafficMirrorTargets(DescribeTrafficMirrorTargetsRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeTrafficMirrorTargetsRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeTrafficMirrorTargetsResponseUnmarshaller.Instance;return Invoke<DescribeTrafficMirrorTargetsResponse>(request, options);}
public virtual ModifyClusterParameterGroupResponse ModifyClusterParameterGroup(ModifyClusterParameterGroupRequest request){var options = new InvokeOptions();options.RequestMarshaller = ModifyClusterParameterGroupRequestMarshaller.Instance;options.ResponseUnmarshaller = ModifyClusterParameterGroupResponseUnmarshaller.Instance;return Invoke<ModifyClusterParameterGroupResponse>(request, options);}
public long getTotalSLLLookaheadOps(){DecisionInfo[] decisions = atnSimulator.getDecisionInfo();long k = 0;for (int i = 0; i < decisions.Length; i++){k += decisions[i].SLL_TotalLook;}return k;}
public static int idealIntArraySize(int need){return idealByteArraySize(need * 4) / 4;}
public StopInstancesRequest(List<string> instanceIds){_instanceIds = instanceIds;}
public virtual bool isIndeterminate(){lock (this){return mIndeterminate;}}
public virtual CreateImportJobResponse CreateImportJob(CreateImportJobRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateImportJobRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateImportJobResponseUnmarshaller.Instance;return Invoke<CreateImportJobResponse>(request, options);}
public override void Write(ILittleEndianOutput out1){out1.WriteByte(Sid + PtgClass);WriteCoordinates(out1);}
public virtual DeleteReceiptRuleResponse DeleteReceiptRule(DeleteReceiptRuleRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteReceiptRuleRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteReceiptRuleResponseUnmarshaller.Instance;return Invoke<DeleteReceiptRuleResponse>(request, options);}
public virtual DescribeFleetCapacityResponse DescribeFleetCapacity(DescribeFleetCapacityRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeFleetCapacityRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeFleetCapacityResponseUnmarshaller.Instance;return Invoke<DescribeFleetCapacityResponse>(request, options);}
public virtual PutIntegrationResponseResponse PutIntegrationResponse(PutIntegrationResponseRequest request){var options = new InvokeOptions();options.RequestMarshaller = PutIntegrationResponseRequestMarshaller.Instance;options.ResponseUnmarshaller = PutIntegrationResponseResponseUnmarshaller.Instance;return Invoke<PutIntegrationResponseResponse>(request, options);}
public MergeAlgorithm(DiffAlgorithm diff){this.diffAlg = diff;}
public bool Matches(char c){return char.IsDigit(c);}
public virtual long EstimateBytesUsed(){return this.bytesUsed;}
protected internal StashCreateCommand(Repository repo) : base(repo){person = new PersonIdent(repo);}
public override void Write(byte[] b, int off, int len){if ((off < 0) || (off > b.Length) || (len < 0) ||((off + len) > b.Length) || ((off + len) < 0)){throw new IndexOutOfRangeException();}else if (len == 0){return;}do{CreateBlockIfNeeded();int writeBytes = Math.Min(buffer.Remaining(), len);buffer.Write(b, off, writeBytes);off += writeBytes;len -= writeBytes;} while (len > 0);}
public short ClearShort(short holder){return (short)this.Clear(holder);}
public DeltaIndex(byte[] sourceBuffer){src = sourceBuffer;DeltaIndexScanner scan = new DeltaIndexScanner(src, src.Length);table = scan.table;tableMask = scan.tableMask;entries = new long[1 + CountEntries(scan)];CopyEntries(scan);}
public Count(){_predicate = defaultPredicate;}
public virtual CreateIntegrationResponse CreateIntegration(CreateIntegrationRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateIntegrationRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateIntegrationResponseUnmarshaller.Instance;return Invoke<CreateIntegrationResponse>(request, options);}
public override void Mark(int ignoredReadlimit){delegate1.Mark(ignoredReadlimit);}
public CollatedTermAttributeImpl(Collator collator){this.collator = (Collator)collator.Clone();}
public override java.nio.CharBuffer duplicate(){return copy(this, _mark);}
public virtual ModifyCertificatesResponse ModifyCertificates(ModifyCertificatesRequest request){var options = new InvokeOptions();options.RequestMarshaller = ModifyCertificatesRequestMarshaller.Instance;options.ResponseUnmarshaller = ModifyCertificatesResponseUnmarshaller.Instance;return Invoke<ModifyCertificatesResponse>(request, options);}
public override java.util.Collection<V> values(){java.util.Collection<V> vs = _values;return (vs != null) ? vs : (_values = new java.util.HashMap<K, V>.Values(this));}
public override bool add(E @object){lock (this){if (elementCount == elementData.Length){growByOne();}elementData[elementCount++] = @object;modCount++;return true;}}
public virtual ListDeliverabilityTestReportsResponse ListDeliverabilityTestReports(ListDeliverabilityTestReportsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListDeliverabilityTestReportsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListDeliverabilityTestReportsResponseUnmarshaller.Instance;return Invoke<ListDeliverabilityTestReportsResponse>(request, options);}
public string GetTokenName(int t){if (t == TokenConstants.EOF){return "EOF";}IVocabulary vocabulary = parser != null ? parser.Vocabulary : Vocabulary.EmptyVocabulary;String displayName = vocabulary.GetDisplayName(t);if (displayName.Equals(t.ToString())){return displayName;}return displayName + "<" + t + ">";}
public GetHostedZoneRequest(string id){_id = id;}
public virtual ListOutgoingTypedLinksResponse ListOutgoingTypedLinks(ListOutgoingTypedLinksRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListOutgoingTypedLinksRequestMarshaller.Instance;options.ResponseUnmarshaller = ListOutgoingTypedLinksResponseUnmarshaller.Instance;return Invoke<ListOutgoingTypedLinksResponse>(request, options);}
public BatchDeleteAttributesRequest(string domainName, List<DeletableItem> items){_domainName = domainName;_items = items;}
public short ReadShort(){return _in.ReadShort();}
public override java.nio.LongBuffer compact(){throw new java.nio.ReadOnlyBufferException();}
public UnbufferedCharStream(TextReader input, int bufferSize): this(bufferSize){this.input = input;Fill(1);}
public virtual NGit.Api.CleanCommand SetPaths(ICollection<string> paths){this.paths = paths;return this;}
public virtual long Hash1(char c){long p = 1099511628211L;long hash = unchecked((long)0xcbf29ce484222325L);hash = (hash ^ (c & 0x00FF)) * p;hash = (hash ^ (c >> 8)) * p;hash += hash << 13;hash ^= hash >> 7;hash += hash << 3;hash ^= hash >> 17;hash += hash << 5;return hash;}
public virtual void Split(){bool success = false;DirectoryReader reader = DirectoryReader.Open(input);try{CreateIndex(config1, dir1, reader, docsInFirstIndex, false);CreateIndex(config2, dir2, reader, docsInFirstIndex, true);success = true;}finally{if (success){IOUtils.Dispose(reader);}else{IOUtils.DisposeWhileHandlingException(reader);}}}
public static java.nio.IntBuffer wrap(int[] array_1){return wrap(array_1, 0, array_1.Length);}
public override string ToString(){string padd = GetPadding();StringBuilder sb = new StringBuilder(base.ToString());sb.Append(parallel ? " [" : " {");sb.Append(NEW_LINE);foreach (PerfTask task in tasks){sb.Append(task.ToString());sb.Append(NEW_LINE);}sb.Append(padd);sb.Append(!letChildReport ? ">" : (parallel ? "]" : "}"));if (fixedTime){sb.AppendFormat(CultureInfo.InvariantCulture, " {0:N}s", runTimeSec);}else if (repetitions > 1){sb.Append(" * " + repetitions);}else if (repetitions == REPEAT_EXHAUST){sb.Append(" * EXHAUST");}if (rate > 0){sb.Append(",  rate: " + rate + "/" + (perMin ? "min" : "sec"));}if (RunInBackground){sb.Append(" &");int x = BackgroundDeltaPriority;if (x != 0){sb.Append(x);}}return sb.ToString();}
public BytesRef(int capacity){this.bytes = new byte[capacity];}
public virtual StartMatchBackfillResponse StartMatchBackfill(StartMatchBackfillRequest request){var options = new InvokeOptions();options.RequestMarshaller = StartMatchBackfillRequestMarshaller.Instance;options.ResponseUnmarshaller = StartMatchBackfillResponseUnmarshaller.Instance;return Invoke<StartMatchBackfillResponse>(request, options);}
public virtual DescribeImagesResponse DescribeImages(DescribeImagesRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeImagesRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeImagesResponseUnmarshaller.Instance;return Invoke<DescribeImagesResponse>(request, options);}
public override void setLength(int length_1){lock (this){base.setLength(length_1);}}
public virtual StartSmartHomeApplianceDiscoveryResponse StartSmartHomeApplianceDiscovery(StartSmartHomeApplianceDiscoveryRequest request){var options = new InvokeOptions();options.RequestMarshaller = StartSmartHomeApplianceDiscoveryRequestMarshaller.Instance;options.ResponseUnmarshaller = StartSmartHomeApplianceDiscoveryResponseUnmarshaller.Instance;return Invoke<StartSmartHomeApplianceDiscoveryResponse>(request, options);}
public RuleTransition(RuleStartState ruleStart, int ruleIndex, int precedence, ATNState followState): base(ruleStart){this.ruleIndex = ruleIndex;this.precedence = precedence;this.followState = followState;}
public void ReadFully(byte[] buf, int off, int len){_in.ReadFully(buf, off, len);}
public UserInputQueryBuilder(QueryParser parser){this.unSafeParser = parser;}
public virtual DescribeIdentityPoolResponse DescribeIdentityPool(DescribeIdentityPoolRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeIdentityPoolRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeIdentityPoolResponseUnmarshaller.Instance;return Invoke<DescribeIdentityPoolResponse>(request, options);}
public CompositeReaderContext Build(){return (CompositeReaderContext)Build(null, reader, 0, 0);}
public virtual CountPendingActivityTasksResponse CountPendingActivityTasks(CountPendingActivityTasksRequest request){var options = new InvokeOptions();options.RequestMarshaller = CountPendingActivityTasksRequestMarshaller.Instance;options.ResponseUnmarshaller = CountPendingActivityTasksResponseUnmarshaller.Instance;return Invoke<CountPendingActivityTasksResponse>(request, options);}
public virtual DeleteTrialComponentResponse DeleteTrialComponent(DeleteTrialComponentRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteTrialComponentRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteTrialComponentResponseUnmarshaller.Instance;return Invoke<DeleteTrialComponentResponse>(request, options);}
public override string ToString(){var children = GetChildren();if (children == null || children.Count == 0)return "<tokenizedphrase/>";StringBuilder sb = new StringBuilder();sb.Append("<tokenizedtphrase>");foreach (IQueryNode child in children){sb.Append("\n");sb.Append(child.ToString());}sb.Append("\n</tokenizedphrase>");return sb.ToString();}
public TermsEnumIndex(TermsEnum termsEnum, int subIndex){this.TermsEnum = termsEnum;this.SubIndex = subIndex;}
public virtual int getHeight(){return mBitmap.getHeight();}
public Restrictions(GeoRestriction geoRestriction){_geoRestriction = geoRestriction;}
public virtual SendBulkTemplatedEmailResponse SendBulkTemplatedEmail(SendBulkTemplatedEmailRequest request){var options = new InvokeOptions();options.RequestMarshaller = SendBulkTemplatedEmailRequestMarshaller.Instance;options.ResponseUnmarshaller = SendBulkTemplatedEmailResponseUnmarshaller.Instance;return Invoke<SendBulkTemplatedEmailResponse>(request, options);}
public PagedMutable(long size, int pageSize, int bitsPerValue, float acceptableOverheadRatio): this(size, pageSize, PackedInt32s.FastestFormatAndBits(pageSize, bitsPerValue, acceptableOverheadRatio)){FillPages();}
public GetLibraryRequest(): base("CloudPhoto", "2017-07-11", "GetLibrary", "cloudphoto", "openAPI"){Protocol = ProtocolType.HTTPS;}
public static void fill(long[] array, long value){{for (int i = 0; i < array.Length; i++){array[i] = value;}}}
public virtual DeleteAliasResponse DeleteAlias(DeleteAliasRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteAliasRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteAliasResponseUnmarshaller.Instance;return Invoke<DeleteAliasResponse>(request, options);}
public override object Merge(object first, object second){IList<T> outputList = new JCG.List<T>();if (!(first is IList<T> firstList)){outputList.Add((T)first);}else{foreach (T value in firstList){outputList.Add(value);}}if (!(second is IList<T> secondList)){outputList.Add((T)second);}else{foreach (T value in secondList){outputList.Add(value);}}return outputList;}
public NPOI.SS.UserModel.IClientAnchor CreateClientAnchor(){return new HSSFClientAnchor();}
public virtual ListQualificationRequestsResponse ListQualificationRequests(ListQualificationRequestsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListQualificationRequestsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListQualificationRequestsResponseUnmarshaller.Instance;return Invoke<ListQualificationRequestsResponse>(request, options);}
public override int Read(){if (ptr == data.Length){return -1;}return data[ptr++] & unchecked((int)(0xff));}
public virtual bool IsSupported(int bitsPerValue){return bitsPerValue >= 1 && bitsPerValue <= 64;}
public ReleaseAddressRequest(string publicIp){_publicIp = publicIp;}
public virtual DeleteClusterSecurityGroupResponse DeleteClusterSecurityGroup(DeleteClusterSecurityGroupRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteClusterSecurityGroupRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteClusterSecurityGroupResponseUnmarshaller.Instance;return Invoke<DeleteClusterSecurityGroupResponse>(request, options);}
public virtual CreateProfilingGroupResponse CreateProfilingGroup(CreateProfilingGroupRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateProfilingGroupRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateProfilingGroupResponseUnmarshaller.Instance;return Invoke<CreateProfilingGroupResponse>(request, options);}
public java.util.regex.MatchResult toMatchResult(){ensureMatch();return new java.util.regex.MatchResultImpl(input, matchOffsets);}
public virtual DescribeInstallationMediaResponse DescribeInstallationMedia(DescribeInstallationMediaRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeInstallationMediaRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeInstallationMediaResponseUnmarshaller.Instance;return Invoke<DescribeInstallationMediaResponse>(request, options);}
public override string ToString(){return "INDEX_DIFF_FILTER";}
public override Type GetListenerType(){return typeof(ConfigChangedListener);}
public virtual StopDBClusterResponse StopDBCluster(StopDBClusterRequest request){var options = new InvokeOptions();options.RequestMarshaller = StopDBClusterRequestMarshaller.Instance;options.ResponseUnmarshaller = StopDBClusterResponseUnmarshaller.Instance;return Invoke<StopDBClusterResponse>(request, options);}
public virtual string GetName(){return name;}
public override java.io.Writer append(char c){write(c);return this;}
public virtual AcceptVpcPeeringConnectionResponse AcceptVpcPeeringConnection(AcceptVpcPeeringConnectionRequest request){var options = new InvokeOptions();options.RequestMarshaller = AcceptVpcPeeringConnectionRequestMarshaller.Instance;options.ResponseUnmarshaller = AcceptVpcPeeringConnectionResponseUnmarshaller.Instance;return Invoke<AcceptVpcPeeringConnectionResponse>(request, options);}
public override int size(){return a.Length;}
public JapaneseTokenizerFactory(IDictionary<string, string> args): base(args){Enum.TryParse(Get(args, MODE, JapaneseTokenizer.DEFAULT_MODE.ToString()), true, out mode);userDictionaryPath = Get(args, USER_DICT_PATH);userDictionaryEncoding = Get(args, USER_DICT_ENCODING);discardPunctuation = GetBoolean(args, DISCARD_PUNCTUATION, true);if (args.Count > 0){throw new ArgumentException("Unknown parameters: " + args);}}
public override void close(){lock (@lock){if (isClosed()){return;}System.Exception thrown = null;try{flushInternal();}catch (System.Exception e){thrown = e;}buf = null;try{@out.close();}catch (System.Exception e){if (thrown == null){thrown = e;}}@out = null;if (thrown != null){Sharpen.Util.Throw(thrown);}}}
public UnmonitorInstancesRequest(List<string> instanceIds){_instanceIds = instanceIds;}
public override void Dispatch(IndexChangedListener listener){listener.OnIndexChanged(this);}
public NameRecord GetNameRecord(int index){return (NameRecord)_definedNames[index];}
public Name(NameRecord nameRecord, int index){_nameRecord = nameRecord;_index = index;}
public virtual ClaimGameServerResponse ClaimGameServer(ClaimGameServerRequest request){var options = new InvokeOptions();options.RequestMarshaller = ClaimGameServerRequestMarshaller.Instance;options.ResponseUnmarshaller = ClaimGameServerResponseUnmarshaller.Instance;return Invoke<ClaimGameServerResponse>(request, options);}
public virtual DescribeScalingParametersResponse DescribeScalingParameters(DescribeScalingParametersRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeScalingParametersRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeScalingParametersResponseUnmarshaller.Instance;return Invoke<DescribeScalingParametersResponse>(request, options);}
public NGramDistance(int size){this.n = size;}
public virtual DetectDominantLanguageResponse DetectDominantLanguage(DetectDominantLanguageRequest request){var options = new InvokeOptions();options.RequestMarshaller = DetectDominantLanguageRequestMarshaller.Instance;options.ResponseUnmarshaller = DetectDominantLanguageResponseUnmarshaller.Instance;return Invoke<DetectDominantLanguageResponse>(request, options);}
public virtual void Consume(){if (LA(1) == IntStreamConstants.EOF){throw new InvalidOperationException("cannot consume EOF");}lastChar = data[p];if (p == n - 1 && numMarkers == 0){n = 0;p = -1;lastCharBufferStart = lastChar;}p++;currentCharIndex++;Sync(1);}
public override TokenStream Create(TokenStream input){return dictionary == null ? input : new DictionaryCompoundWordTokenFilter(m_luceneMatchVersion, input, dictionary, minWordSize, minSubwordSize, maxSubwordSize, onlyLongestMatch);}
