public int GetHeight(){return height;}
public virtual DescribeReservedInstancesResponse DescribeReservedInstances(){return DescribeReservedInstances(new DescribeReservedInstancesRequest());}
public void Serialize(ILittleEndianOutput out1){out1.WriteShort(_extBookIndex);out1.WriteShort(_firstSheetIndex);out1.WriteShort(_lastSheetIndex);}
public virtual K getKey(){return key;}
public virtual void SetPackedGitMMAP(bool usemmap){packedGitMMAP = usemmap;}
public virtual ListIdentityPoolUsageResponse ListIdentityPoolUsage(ListIdentityPoolUsageRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListIdentityPoolUsageRequestMarshaller.Instance;options.ResponseUnmarshaller = ListIdentityPoolUsageResponseUnmarshaller.Instance;return Invoke<ListIdentityPoolUsageResponse>(request, options);}
public virtual TerminateInstancesResponse TerminateInstances(TerminateInstancesRequest request){var options = new InvokeOptions();options.RequestMarshaller = TerminateInstancesRequestMarshaller.Instance;options.ResponseUnmarshaller = TerminateInstancesResponseUnmarshaller.Instance;return Invoke<TerminateInstancesResponse>(request, options);}
public virtual NGit.ObjectDatabase NewCachedDatabase(){return this;}
public FileTreeIterator(FilePath root, FS fs, WorkingTreeOptions options) : base(options){directory = root;this.fs = fs;Init(Entries());}
public static void Register(TransportProtocol proto){protocols.Add(0, new JavaWeakReference<TransportProtocol>(proto));}
public virtual DescribeVolumeStatusResponse DescribeVolumeStatus(DescribeVolumeStatusRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeVolumeStatusRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeVolumeStatusResponseUnmarshaller.Instance;return Invoke<DescribeVolumeStatusResponse>(request, options);}
public virtual DescribeTrainingJobResponse DescribeTrainingJob(DescribeTrainingJobRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeTrainingJobRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeTrainingJobResponseUnmarshaller.Instance;return Invoke<DescribeTrainingJobResponse>(request, options);}
public virtual UpdateCustomVerificationEmailTemplateResponse UpdateCustomVerificationEmailTemplate(UpdateCustomVerificationEmailTemplateRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateCustomVerificationEmailTemplateRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateCustomVerificationEmailTemplateResponseUnmarshaller.Instance;return Invoke<UpdateCustomVerificationEmailTemplateResponse>(request, options);}
public override void Decode(byte[] blocks, int blocksOffset, int[] values, int valuesOffset, int iterations){for (int j = 0; j < iterations; ++j){values[valuesOffset++] = blocks[blocksOffset++] & 0xFF;}}
public static int CommitMessage(byte[] b, int ptr){int sz = b.Length;if (ptr == 0){ptr += 46;}while (ptr < sz && b[ptr] == 'p'){ptr += 48;}return TagMessage(b, ptr);}
public CreateAlbumRequest(): base("CloudPhoto", "2017-07-11", "CreateAlbum", "cloudphoto", "openAPI"){Protocol = ProtocolType.HTTPS;}
public virtual CreateEnvironmentResponse CreateEnvironment(CreateEnvironmentRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateEnvironmentRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateEnvironmentResponseUnmarshaller.Instance;return Invoke<CreateEnvironmentResponse>(request, options);}
public override V put(K key, V value){if (!this.isInBounds(key)){throw this.outOfBounds(key, this.fromBound, this.toBound);}return this._enclosing.putInternal(key, value);}
public static String GetFromUnicodeLE(byte[] str){if (str.Length == 0) { return ""; }return GetFromUnicodeLE(str, 0, str.Length / 2);}
public override void Add(RevCommit c){BlockRevQueue.Block b = tail;if (b == null){b = free.NewBlock();b.Add(c);head = b;tail = b;return;}else{if (b.IsFull()){b = free.NewBlock();tail.next = b;tail = b;}}b.Add(c);}
public virtual UpdateFieldLevelEncryptionProfileResponse UpdateFieldLevelEncryptionProfile(UpdateFieldLevelEncryptionProfileRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateFieldLevelEncryptionProfileRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateFieldLevelEncryptionProfileResponseUnmarshaller.Instance;return Invoke<UpdateFieldLevelEncryptionProfileResponse>(request, options);}
public override string ToString(){return "Token(\"" + new string(surfaceForm, offset, length) + "\" pos=" + position + " length=" + length +" posLen=" + positionLength + " type=" + type + " wordId=" + wordId +" leftID=" + dictionary.GetLeftId(wordId) + ")";}
public virtual DescribeInstanceTypesResponse DescribeInstanceTypes(DescribeInstanceTypesRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeInstanceTypesRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeInstanceTypesResponseUnmarshaller.Instance;return Invoke<DescribeInstanceTypesResponse>(request, options);}
public java.nio.charset.CoderResult flush(java.nio.CharBuffer @out){if (status != END && status != INIT){throw new System.InvalidOperationException();}java.nio.charset.CoderResult result = implFlush(@out);if (result == java.nio.charset.CoderResult.UNDERFLOW){status = FLUSH;}return result;}
public SeriesRecord(RecordInputStream in1){field_1_categoryDataType = in1.ReadShort();field_2_valuesDataType = in1.ReadShort();field_3_numCategories = in1.ReadShort();field_4_numValues = in1.ReadShort();field_5_bubbleSeriesType = in1.ReadShort();field_6_numBubbleValues = in1.ReadShort();}
public virtual void setProgress(int progress){lock (this){setProgress(progress, false);}}
public virtual void SetKeepEmpty(bool empty){keepEmpty = empty;}
public String ToFormulaString(IFormulaRenderingWorkbook book){return ExternSheetNameResolver.PrependSheetName(book, field_1_index_extern_sheet, FormatReferenceAsString());}
public virtual RevBlob LookupBlob(AnyObjectId id){RevBlob c = (RevBlob)objects.Get(id);if (c == null){c = new RevBlob(id);objects.Add(c);}return c;}
public override java.nio.ByteBuffer put(byte b){throw new java.nio.ReadOnlyBufferException();}
public virtual CreateSmsTemplateResponse CreateSmsTemplate(CreateSmsTemplateRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateSmsTemplateRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateSmsTemplateResponseUnmarshaller.Instance;return Invoke<CreateSmsTemplateResponse>(request, options);}
public static XmlDocument LoadXML(TextReader input){XmlDocument result = new XmlDocument();try{result.Load(input);}catch (Exception se){throw new Exception("Error parsing file:" + se, se);}return result;}
public E next(){if (iterator.nextIndex() < end){return iterator.next();}throw new java.util.NoSuchElementException();}
public virtual V getValue(){return value;}
public virtual ListUserHierarchyGroupsResponse ListUserHierarchyGroups(ListUserHierarchyGroupsRequest request){var options = new InvokeOptions();options.RequestMarshaller = ListUserHierarchyGroupsRequestMarshaller.Instance;options.ResponseUnmarshaller = ListUserHierarchyGroupsResponseUnmarshaller.Instance;return Invoke<ListUserHierarchyGroupsResponse>(request, options);}
public UnmappableCharacterException(int length){this.inputLength = length;}
public virtual DescribeProfilingGroupResponse DescribeProfilingGroup(DescribeProfilingGroupRequest request){var options = new InvokeOptions();options.RequestMarshaller = DescribeProfilingGroupRequestMarshaller.Instance;options.ResponseUnmarshaller = DescribeProfilingGroupResponseUnmarshaller.Instance;return Invoke<DescribeProfilingGroupResponse>(request, options);}
public virtual CreateDomainResponse CreateDomain(CreateDomainRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateDomainRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateDomainResponseUnmarshaller.Instance;return Invoke<CreateDomainResponse>(request, options);}
public virtual UpdateBasePathMappingResponse UpdateBasePathMapping(UpdateBasePathMappingRequest request){var options = new InvokeOptions();options.RequestMarshaller = UpdateBasePathMappingRequestMarshaller.Instance;options.ResponseUnmarshaller = UpdateBasePathMappingResponseUnmarshaller.Instance;return Invoke<UpdateBasePathMappingResponse>(request, options);}
public virtual ListMetricsResponse ListMetrics(){return ListMetrics(new ListMetricsRequest());}
public virtual DeleteRelationalDatabaseResponse DeleteRelationalDatabase(DeleteRelationalDatabaseRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteRelationalDatabaseRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteRelationalDatabaseResponseUnmarshaller.Instance;return Invoke<DeleteRelationalDatabaseResponse>(request, options);}
public override string ToString(){return GetType().ToString() + ": " + GetOldId().Name + " " + GetNewId().Name + " "+ GetRefName();}
public override java.nio.ByteBuffer slice(){return new java.nio.ReadOnlyHeapByteBuffer(backingArray, remaining(), offset + _position);}
public virtual ResetNetworkInterfaceAttributeResponse ResetNetworkInterfaceAttribute(ResetNetworkInterfaceAttributeRequest request){var options = new InvokeOptions();options.RequestMarshaller = ResetNetworkInterfaceAttributeRequestMarshaller.Instance;options.ResponseUnmarshaller = ResetNetworkInterfaceAttributeResponseUnmarshaller.Instance;return Invoke<ResetNetworkInterfaceAttributeResponse>(request, options);}
public virtual int ByteAt(int idx){return bytes[idx].Value;}
public override bool Equals(object @object){if (this == @object){return true;}if (@object is java.util.MapClass.Entry<K, V>){java.util.MapClass.Entry<object, object> entry = (java.util.MapClass.Entry<object, object>)@object;return ((object)key == null ? entry.getKey() == null : key.Equals(entry.getKey())) && ((object)value == null ? entry.getValue() == null : value.Equals(entry.getValue()));}return false;}
public virtual CreateJourneyResponse CreateJourney(CreateJourneyRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateJourneyRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateJourneyResponseUnmarshaller.Instance;return Invoke<CreateJourneyResponse>(request, options);}
public virtual ICollection<string> GetNames(string section, string subsection){return GetState().GetNames(section, subsection);}
public virtual DeleteLifecycleHookResponse DeleteLifecycleHook(DeleteLifecycleHookRequest request){var options = new InvokeOptions();options.RequestMarshaller = DeleteLifecycleHookRequestMarshaller.Instance;options.ResponseUnmarshaller = DeleteLifecycleHookResponseUnmarshaller.Instance;return Invoke<DeleteLifecycleHookResponse>(request, options);}
public override void Decode(long[] blocks, int blocksOffset, long[] values, int valuesOffset, int iterations){for (int i = 0; i < iterations; ++i){long block = blocks[blocksOffset++];valuesOffset = Decode(block, values, valuesOffset);}}
