public override int Advance(int target){upto++;if (upto == docIDs.Length){return docID_Renamed = NO_MORE_DOCS;}int inc = 10;int nextUpto = upto + 10;int low;int high;while (true){if (nextUpto >= docIDs.Length){low = nextUpto - inc;high = docIDs.Length - 1;break;}if (target <= docIDs[nextUpto]){low = nextUpto - inc;high = nextUpto;break;}inc *= 2;nextUpto += inc;}while (true){if (low > high){upto = low;break;}int mid = (int) ((uint) (low + high) >> 1);int cmp = docIDs[mid] - target;if (cmp < 0){low = mid + 1;}else if (cmp > 0){high = mid - 1;}else{upto = mid;break;}}if (liveDocs != null){while (upto < docIDs.Length){if (liveDocs.Get(docIDs[upto])){break;}upto++;}}if (upto == docIDs.Length){return docID_Renamed = NO_MORE_DOCS;}else{return docID_Renamed = docIDs[upto];}}
public CharVector(int capacity){if (capacity > 0){blockSize = capacity;}else{blockSize = DEFAULT_BLOCK_SIZE;}array = new char[blockSize];n = 0;}
public virtual IList<Tuple<K, V>> GetPairs(){IList<Tuple<K, V>> pairs = new ArrayList<Tuple<K, V>>();foreach (KeyValuePair<K, IList<V>> pair in this){foreach (V value in pair.Value){pairs.Add(Tuple.Create(pair.Key, value));}}return pairs;}
public override object Clone(){return new CompressingTermVectorsReader(this);}
public virtual ResetNetworkInterfaceAttributeResponse ResetNetworkInterfaceAttribute(ResetNetworkInterfaceAttributeRequest request){var options = new InvokeOptions();options.RequestMarshaller = ResetNetworkInterfaceAttributeRequestMarshaller.Instance;options.ResponseUnmarshaller = ResetNetworkInterfaceAttributeResponseUnmarshaller.Instance;return Invoke<ResetNetworkInterfaceAttributeResponse>(request, options);}
public virtual LogCommand Log(){return new LogCommand(repo);}
public string getRawUserInfo(){return userInfo;}
public override TokenStream Create(TokenStream input){return new SoraniStemFilter(input);}
public override java.nio.ByteBuffer put(byte b){throw new java.nio.ReadOnlyBufferException();}
public virtual CreateCacheSubnetGroupResponse CreateCacheSubnetGroup(CreateCacheSubnetGroupRequest request){var options = new InvokeOptions();options.RequestMarshaller = CreateCacheSubnetGroupRequestMarshaller.Instance;options.ResponseUnmarshaller = CreateCacheSubnetGroupResponseUnmarshaller.Instance;return Invoke<CreateCacheSubnetGroupResponse>(request, options);}
public BlankCellRectangleGroup(int firstRowIndex, int firstColumnIndex, int lastColumnIndex){_firstRowIndex = firstRowIndex;_firstColumnIndex = firstColumnIndex;_lastColumnIndex = lastColumnIndex;_lastRowIndex = firstRowIndex;}
public static char[] copyOf(char[] original, int newLength){if (newLength < 0){throw new java.lang.NegativeArraySizeException();}return copyOfRange(original, 0, newLength);}
public override void Validate(){base.Validate();}
public virtual Ent Peek(){if (this.packedIdx < this._enclosing.packed.Size() && this.looseIdx < this._enclosing.loose.Size()){Ref p = this._enclosing.packed.Get(this.packedIdx);Ref l = this._enclosing.loose.Get(this.looseIdx);int cmp = RefComparator.CompareTo(p, l);if (cmp < 0){this.packedIdx++;return this.ToEntry(p);}if (cmp == 0){this.packedIdx++;}this.looseIdx++;return this.ToEntry(this.ResolveLoose(l));}if (this.looseIdx < this._enclosing.loose.Size()){return this.ToEntry(this.ResolveLoose(this._enclosing.loose.Get(this.looseIdx++)));}if (this.packedIdx < this._enclosing.packed.Size()){return this.ToEntry(this._enclosing.packed.Get(this.packedIdx++));}return null;}
public ValueEval GetRef3DEval(Ref3DPxg rptg){SheetRangeEvaluator sre = CreateExternSheetRefEvaluator(rptg.SheetName, rptg.LastSheetName, rptg.ExternalWorkbookNumber);return new LazyRefEval(rptg.Row, rptg.Column, sre);}
public void Serialize(ILittleEndianOutput out1){out1.WriteShort(_extBookIndex);out1.WriteShort(_firstSheetIndex);out1.WriteShort(_lastSheetIndex);}
